name = "light_xtensa_esp"
description = "Xtensa ESP32 light runtime implementation"
version = "0.1.0-dev"

authors = ["Ron Tesler"]
maintainers-logins = ["joebeazelman"]
tags = ["ada", "xtensa", "esp32"]

project-files = "runtime_build.gpr"

[[depends-on]]
gnat_xtensa_elf = "*" # Any compiler targeting Xtensa ESP