name = "light_xtensa_esp"
description = "Xtensa ESP32 light runtime implementation"
version = "0.1.0-dev"

authors = ["Ron Tesler"]
tags = ["ada", "xtensa", "esp32"]
maintainers = ["joebeazelman@github.com", "rowsail@github.com"]
maintainers-logins = ["joebeazelman", "rowsail"]
project-files = "runtime_build.gpr"

[[depends-on]]
gnat_xtensa_esp32_elf = "^14"

[environment.'case(os)']
linux = { XTENSA_GNU_CONFIG.set = "xtensa_esp32s3.so" }
windows = { XTENSA_GNU_CONFIG.set = "xtensa_esp32s3.dll" }
macos = { XTENSA_GNU_CONFIG.set = "xtensa_esp32s3.dylib" }

